### ISSUE TITLE
Organization access lost while linking another GitHub account

### ISSUE THREAD

**Issue by pellizzetti** [porter-dev/porter#781] opened 2021-06-16 01:03 UTC
# Description

I have been using Porter for a while now without any problems, so far I had granted access to only one organization (`rocketseat-star-lab`) and was deploying services either from that org or from my personal account.

Yesterday, I invited a coworker to test Porter, she linked her GitHub and deployed a service from her personal account without any problem.

Today she asked me to grant access to another organization (`Rocketseat`), while accessing the Git Repository page I noticed that my previous integration didn't show any repo, only the message `Error loading repos.`. I shrugged it off, thinking it was probably some visual bug, and went on to the OAuth settings to grant access to this new organization.

Returning to Porter, I couldn't deploy any service from any org anymore. :(

I think I tried everything by now:

- Revoked OAuth access multiple times;
- Cleaned all cookies/storage;
- Tried different browsers.

It either get access to only my personal account or nothing, and I get the message `Error loading repos.`

# Location

- [x] Browser
- [ ] CLI
- [ ] API

# Steps to reproduce

I not really sure if this are the right steps to reproduce as I can't get access to the `rocketseat-star-lab` repos anymore.

1. Link a GitHub account and grant access to one org;
2. Have a second different GitHub account linked;
3. Watch as you lose access to the previous org and can´t ever get it back.

# Additional Details

Screenshot of the issue:
![image](https://user-images.githubusercontent.com/16545335/122139964-80cb1400-ce20-11eb-8570-9572c22a60b5.png)

**Comment by abelanger5** [comment] 2021-06-16 01:33
Thanks for the bug report @pellizzetti, sorry to hear about this. I am unable to reproduce this after linking multiple accounts. I have a few questions follow-up questions which will help me resolve this:

1. Just to confirm, does the organization allow for third-party app access, or did you have to grant access permission to the Porter OAuth app specifically?

> I shrugged it off, thinking it was probably some visual bug, and went on to the OAuth settings to grant access to this new organization

2. Which OAuth settings did you go to? The Github OAuth settings for your organization?

3. How did you revoke OAuth access? Did you remove the Github integration for your account from Porter and link it again?

**Comment by pellizzetti** [comment] 2021-06-16 02:16
Hey @abelanger5! Thanks for taking your time to looking into it. 💜

> 1. Just to confirm, does the organization allow for third-party app access, or did you have to grant access permission to the Porter OAuth app specifically?

`rocketseat-star-lab` allow 3rd party app access. For `Rocketseat`, I had to grant access permission to the Porter OAuth app specifically.

> 2. Which OAuth settings did you go to? The Github OAuth settings for your organization?

I was going through my personal account OAuth settings. I just checked both orgs and Porter is currently approved in both.

> 3. How did you revoke OAuth access? Did you remove the Github integration for your account from Porter and link it again?

I revoked access both from Porter and directly from GitHub, several times, I tried multiple combinations of revoking to no avail.

**Comment by pellizzetti** [comment] 2021-06-16 02:42
Ok, I tried removing third-party application restrictions from `rocketseat-star-lab` org and it worked, it started showing the repos back again (even after reinstating the policy)!

But... it didn't worked for `Rocketseat` org, the only thing I know off the top of my head that these orgs differ is that `Rocketseat` requires two-factor authentication from everyone. Do you think it could be something like that causing some troubles in the integration?

**Comment by abelanger5** [comment] 2021-06-16 13:11
Hmm, I don't _think_ the two-factor authentication would be causing the issue. 

I've tried looking through the [organization guide for approving OAuth apps](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/approving-oauth-apps-for-your-organization) but I'm guessing you already tried this? Perhaps the issue is that there's a pending request for Porter access in Github?

Once you remove the restriction for the `Rocketseat` org, I think the safest bet would be to delete and re-add the integration on Porter.

**Comment by pellizzetti** [comment] 2021-06-16 15:06
> I've tried looking through the organization guide for approving OAuth apps but I'm guessing you already tried this? Perhaps the issue is that there's a pending request for Porter access in Github?

Yeah, I had already tried that.

> Once you remove the restriction for the `Rocketseat` org, I think the safest bet would be to delete and re-add the integration on Porter.

Sadly, it didn´t work. I tried that few times, sometimes disabling 2FA too, no luck.

There's something in this org that breaks the whole integration, but I can't pin point what it is. When I re-add the integration on Porter, I get `Error loading repos.`, denying access to `Rocketseat` restore the integration instantly.

**Comment by pellizzetti** [comment] 2021-06-17 14:33
Hey @abelanger5, we currently have 59 repositories in the `Rocketseat` org.

**Comment by abelanger5** [comment] 2021-07-09 01:04
Hi @pellizzetti, just wanted to provide an update on this. There were quite a few issues due to the Github OAuth app, and we are now transitioning to using Github Apps which should hopefully resolve this specific issue. You can see the full discussion here: #833. 

The Github app will be available to install in your account by July 10th, but the dashboard will only start using the Github app for listing repositories and writing workflow files starting on July 24th, which will give users enough time to transition to the Github app for listing repositories (although existing workflows/applications will continue to work with the OAuth app).

**Comment by abelanger5** [comment] 2021-08-02 12:44
Hi @pellizzetti, this issue should hopefully be resolved by the transition to using Github Apps. See this link for how to set up Github App access: https://docs.porter.run/docs/setting-up-github-app-access. 

Please reopen if you are still seeing issues!

**Closed by abelanger5** 2021-08-02 12:44 UTC
